//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBarter.FruitService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Unit", Namespace="http://localhost/")]
    public enum Unit : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KG = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Adet = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="FruitService.FruitInventorySoap")]
    public interface FruitInventorySoap {
        
        // CODEGEN: Generating message contract since element name ListAllFruitsResult from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ListAllFruits", ReplyAction="*")]
        EBarter.FruitService.ListAllFruitsResponse ListAllFruits(EBarter.FruitService.ListAllFruitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ListAllFruits", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.FruitService.ListAllFruitsResponse> ListAllFruitsAsync(EBarter.FruitService.ListAllFruitsRequest request);
        
        // CODEGEN: Generating message contract since element name fruitName from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/AddFruitPrice", ReplyAction="*")]
        EBarter.FruitService.AddFruitPriceResponse AddFruitPrice(EBarter.FruitService.AddFruitPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/AddFruitPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.FruitService.AddFruitPriceResponse> AddFruitPriceAsync(EBarter.FruitService.AddFruitPriceRequest request);
        
        // CODEGEN: Generating message contract since element name fruitName from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/DeleteFruitPrice", ReplyAction="*")]
        EBarter.FruitService.DeleteFruitPriceResponse DeleteFruitPrice(EBarter.FruitService.DeleteFruitPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/DeleteFruitPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.FruitService.DeleteFruitPriceResponse> DeleteFruitPriceAsync(EBarter.FruitService.DeleteFruitPriceRequest request);
        
        // CODEGEN: Generating message contract since element name fruitName from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/UpdateFruitPrice", ReplyAction="*")]
        EBarter.FruitService.UpdateFruitPriceResponse UpdateFruitPrice(EBarter.FruitService.UpdateFruitPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/UpdateFruitPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.FruitService.UpdateFruitPriceResponse> UpdateFruitPriceAsync(EBarter.FruitService.UpdateFruitPriceRequest request);
        
        // CODEGEN: Generating message contract since element name fruitName from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CalMinFruitCost", ReplyAction="*")]
        EBarter.FruitService.CalMinFruitCostResponse CalMinFruitCost(EBarter.FruitService.CalMinFruitCostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CalMinFruitCost", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.FruitService.CalMinFruitCostResponse> CalMinFruitCostAsync(EBarter.FruitService.CalMinFruitCostRequest request);
        
        // CODEGEN: Generating message contract since element name fruitName from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CalMaxFruitCost", ReplyAction="*")]
        EBarter.FruitService.CalMaxFruitCostResponse CalMaxFruitCost(EBarter.FruitService.CalMaxFruitCostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CalMaxFruitCost", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.FruitService.CalMaxFruitCostResponse> CalMaxFruitCostAsync(EBarter.FruitService.CalMaxFruitCostRequest request);
        
        // CODEGEN: Generating message contract since element name fruitName from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CheckInventory", ReplyAction="*")]
        EBarter.FruitService.CheckInventoryResponse CheckInventory(EBarter.FruitService.CheckInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CheckInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.FruitService.CheckInventoryResponse> CheckInventoryAsync(EBarter.FruitService.CheckInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name fruitName from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/HowMuchMinFruit", ReplyAction="*")]
        EBarter.FruitService.HowMuchMinFruitResponse HowMuchMinFruit(EBarter.FruitService.HowMuchMinFruitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/HowMuchMinFruit", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.FruitService.HowMuchMinFruitResponse> HowMuchMinFruitAsync(EBarter.FruitService.HowMuchMinFruitRequest request);
        
        // CODEGEN: Generating message contract since element name fruitName from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/HowMuchMaxFruit", ReplyAction="*")]
        EBarter.FruitService.HowMuchMaxFruitResponse HowMuchMaxFruit(EBarter.FruitService.HowMuchMaxFruitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/HowMuchMaxFruit", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.FruitService.HowMuchMaxFruitResponse> HowMuchMaxFruitAsync(EBarter.FruitService.HowMuchMaxFruitRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAllFruitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAllFruits", Namespace="http://localhost/", Order=0)]
        public EBarter.FruitService.ListAllFruitsRequestBody Body;
        
        public ListAllFruitsRequest() {
        }
        
        public ListAllFruitsRequest(EBarter.FruitService.ListAllFruitsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListAllFruitsRequestBody {
        
        public ListAllFruitsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAllFruitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAllFruitsResponse", Namespace="http://localhost/", Order=0)]
        public EBarter.FruitService.ListAllFruitsResponseBody Body;
        
        public ListAllFruitsResponse() {
        }
        
        public ListAllFruitsResponse(EBarter.FruitService.ListAllFruitsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class ListAllFruitsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ListAllFruitsResult;
        
        public ListAllFruitsResponseBody() {
        }
        
        public ListAllFruitsResponseBody(string ListAllFruitsResult) {
            this.ListAllFruitsResult = ListAllFruitsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddFruitPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddFruitPrice", Namespace="http://localhost/", Order=0)]
        public EBarter.FruitService.AddFruitPriceRequestBody Body;
        
        public AddFruitPriceRequest() {
        }
        
        public AddFruitPriceRequest(EBarter.FruitService.AddFruitPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class AddFruitPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fruitName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double minfruitPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public EBarter.FruitService.Unit fruitUnit;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double maxfruitPrice;
        
        public AddFruitPriceRequestBody() {
        }
        
        public AddFruitPriceRequestBody(string fruitName, double minfruitPrice, EBarter.FruitService.Unit fruitUnit, double maxfruitPrice) {
            this.fruitName = fruitName;
            this.minfruitPrice = minfruitPrice;
            this.fruitUnit = fruitUnit;
            this.maxfruitPrice = maxfruitPrice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddFruitPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddFruitPriceResponse", Namespace="http://localhost/", Order=0)]
        public EBarter.FruitService.AddFruitPriceResponseBody Body;
        
        public AddFruitPriceResponse() {
        }
        
        public AddFruitPriceResponse(EBarter.FruitService.AddFruitPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class AddFruitPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddFruitPriceResult;
        
        public AddFruitPriceResponseBody() {
        }
        
        public AddFruitPriceResponseBody(bool AddFruitPriceResult) {
            this.AddFruitPriceResult = AddFruitPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFruitPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFruitPrice", Namespace="http://localhost/", Order=0)]
        public EBarter.FruitService.DeleteFruitPriceRequestBody Body;
        
        public DeleteFruitPriceRequest() {
        }
        
        public DeleteFruitPriceRequest(EBarter.FruitService.DeleteFruitPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class DeleteFruitPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fruitName;
        
        public DeleteFruitPriceRequestBody() {
        }
        
        public DeleteFruitPriceRequestBody(string fruitName) {
            this.fruitName = fruitName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFruitPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFruitPriceResponse", Namespace="http://localhost/", Order=0)]
        public EBarter.FruitService.DeleteFruitPriceResponseBody Body;
        
        public DeleteFruitPriceResponse() {
        }
        
        public DeleteFruitPriceResponse(EBarter.FruitService.DeleteFruitPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class DeleteFruitPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteFruitPriceResult;
        
        public DeleteFruitPriceResponseBody() {
        }
        
        public DeleteFruitPriceResponseBody(bool DeleteFruitPriceResult) {
            this.DeleteFruitPriceResult = DeleteFruitPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFruitPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFruitPrice", Namespace="http://localhost/", Order=0)]
        public EBarter.FruitService.UpdateFruitPriceRequestBody Body;
        
        public UpdateFruitPriceRequest() {
        }
        
        public UpdateFruitPriceRequest(EBarter.FruitService.UpdateFruitPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class UpdateFruitPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fruitName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double minFruitPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double maxFruitPrice;
        
        public UpdateFruitPriceRequestBody() {
        }
        
        public UpdateFruitPriceRequestBody(string fruitName, double minFruitPrice, double maxFruitPrice) {
            this.fruitName = fruitName;
            this.minFruitPrice = minFruitPrice;
            this.maxFruitPrice = maxFruitPrice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateFruitPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateFruitPriceResponse", Namespace="http://localhost/", Order=0)]
        public EBarter.FruitService.UpdateFruitPriceResponseBody Body;
        
        public UpdateFruitPriceResponse() {
        }
        
        public UpdateFruitPriceResponse(EBarter.FruitService.UpdateFruitPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class UpdateFruitPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateFruitPriceResult;
        
        public UpdateFruitPriceResponseBody() {
        }
        
        public UpdateFruitPriceResponseBody(bool UpdateFruitPriceResult) {
            this.UpdateFruitPriceResult = UpdateFruitPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalMinFruitCostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalMinFruitCost", Namespace="http://localhost/", Order=0)]
        public EBarter.FruitService.CalMinFruitCostRequestBody Body;
        
        public CalMinFruitCostRequest() {
        }
        
        public CalMinFruitCostRequest(EBarter.FruitService.CalMinFruitCostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CalMinFruitCostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fruitName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double fruitQuantity;
        
        public CalMinFruitCostRequestBody() {
        }
        
        public CalMinFruitCostRequestBody(string fruitName, double fruitQuantity) {
            this.fruitName = fruitName;
            this.fruitQuantity = fruitQuantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalMinFruitCostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalMinFruitCostResponse", Namespace="http://localhost/", Order=0)]
        public EBarter.FruitService.CalMinFruitCostResponseBody Body;
        
        public CalMinFruitCostResponse() {
        }
        
        public CalMinFruitCostResponse(EBarter.FruitService.CalMinFruitCostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CalMinFruitCostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CalMinFruitCostResult;
        
        public CalMinFruitCostResponseBody() {
        }
        
        public CalMinFruitCostResponseBody(double CalMinFruitCostResult) {
            this.CalMinFruitCostResult = CalMinFruitCostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalMaxFruitCostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalMaxFruitCost", Namespace="http://localhost/", Order=0)]
        public EBarter.FruitService.CalMaxFruitCostRequestBody Body;
        
        public CalMaxFruitCostRequest() {
        }
        
        public CalMaxFruitCostRequest(EBarter.FruitService.CalMaxFruitCostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CalMaxFruitCostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fruitName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double fruitQuantity;
        
        public CalMaxFruitCostRequestBody() {
        }
        
        public CalMaxFruitCostRequestBody(string fruitName, double fruitQuantity) {
            this.fruitName = fruitName;
            this.fruitQuantity = fruitQuantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalMaxFruitCostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalMaxFruitCostResponse", Namespace="http://localhost/", Order=0)]
        public EBarter.FruitService.CalMaxFruitCostResponseBody Body;
        
        public CalMaxFruitCostResponse() {
        }
        
        public CalMaxFruitCostResponse(EBarter.FruitService.CalMaxFruitCostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CalMaxFruitCostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CalMaxFruitCostResult;
        
        public CalMaxFruitCostResponseBody() {
        }
        
        public CalMaxFruitCostResponseBody(double CalMaxFruitCostResult) {
            this.CalMaxFruitCostResult = CalMaxFruitCostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckInventory", Namespace="http://localhost/", Order=0)]
        public EBarter.FruitService.CheckInventoryRequestBody Body;
        
        public CheckInventoryRequest() {
        }
        
        public CheckInventoryRequest(EBarter.FruitService.CheckInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CheckInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fruitName;
        
        public CheckInventoryRequestBody() {
        }
        
        public CheckInventoryRequestBody(string fruitName) {
            this.fruitName = fruitName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckInventoryResponse", Namespace="http://localhost/", Order=0)]
        public EBarter.FruitService.CheckInventoryResponseBody Body;
        
        public CheckInventoryResponse() {
        }
        
        public CheckInventoryResponse(EBarter.FruitService.CheckInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CheckInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckInventoryResult;
        
        public CheckInventoryResponseBody() {
        }
        
        public CheckInventoryResponseBody(string CheckInventoryResult) {
            this.CheckInventoryResult = CheckInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HowMuchMinFruitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HowMuchMinFruit", Namespace="http://localhost/", Order=0)]
        public EBarter.FruitService.HowMuchMinFruitRequestBody Body;
        
        public HowMuchMinFruitRequest() {
        }
        
        public HowMuchMinFruitRequest(EBarter.FruitService.HowMuchMinFruitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class HowMuchMinFruitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fruitName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double totalBudget;
        
        public HowMuchMinFruitRequestBody() {
        }
        
        public HowMuchMinFruitRequestBody(string fruitName, double totalBudget) {
            this.fruitName = fruitName;
            this.totalBudget = totalBudget;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HowMuchMinFruitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HowMuchMinFruitResponse", Namespace="http://localhost/", Order=0)]
        public EBarter.FruitService.HowMuchMinFruitResponseBody Body;
        
        public HowMuchMinFruitResponse() {
        }
        
        public HowMuchMinFruitResponse(EBarter.FruitService.HowMuchMinFruitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class HowMuchMinFruitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double HowMuchMinFruitResult;
        
        public HowMuchMinFruitResponseBody() {
        }
        
        public HowMuchMinFruitResponseBody(double HowMuchMinFruitResult) {
            this.HowMuchMinFruitResult = HowMuchMinFruitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HowMuchMaxFruitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HowMuchMaxFruit", Namespace="http://localhost/", Order=0)]
        public EBarter.FruitService.HowMuchMaxFruitRequestBody Body;
        
        public HowMuchMaxFruitRequest() {
        }
        
        public HowMuchMaxFruitRequest(EBarter.FruitService.HowMuchMaxFruitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class HowMuchMaxFruitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fruitName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double totalBudget;
        
        public HowMuchMaxFruitRequestBody() {
        }
        
        public HowMuchMaxFruitRequestBody(string fruitName, double totalBudget) {
            this.fruitName = fruitName;
            this.totalBudget = totalBudget;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HowMuchMaxFruitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HowMuchMaxFruitResponse", Namespace="http://localhost/", Order=0)]
        public EBarter.FruitService.HowMuchMaxFruitResponseBody Body;
        
        public HowMuchMaxFruitResponse() {
        }
        
        public HowMuchMaxFruitResponse(EBarter.FruitService.HowMuchMaxFruitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class HowMuchMaxFruitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double HowMuchMaxFruitResult;
        
        public HowMuchMaxFruitResponseBody() {
        }
        
        public HowMuchMaxFruitResponseBody(double HowMuchMaxFruitResult) {
            this.HowMuchMaxFruitResult = HowMuchMaxFruitResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FruitInventorySoapChannel : EBarter.FruitService.FruitInventorySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FruitInventorySoapClient : System.ServiceModel.ClientBase<EBarter.FruitService.FruitInventorySoap>, EBarter.FruitService.FruitInventorySoap {
        
        public FruitInventorySoapClient() {
        }
        
        public FruitInventorySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FruitInventorySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FruitInventorySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FruitInventorySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.FruitService.ListAllFruitsResponse EBarter.FruitService.FruitInventorySoap.ListAllFruits(EBarter.FruitService.ListAllFruitsRequest request) {
            return base.Channel.ListAllFruits(request);
        }
        
        public string ListAllFruits() {
            EBarter.FruitService.ListAllFruitsRequest inValue = new EBarter.FruitService.ListAllFruitsRequest();
            inValue.Body = new EBarter.FruitService.ListAllFruitsRequestBody();
            EBarter.FruitService.ListAllFruitsResponse retVal = ((EBarter.FruitService.FruitInventorySoap)(this)).ListAllFruits(inValue);
            return retVal.Body.ListAllFruitsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.FruitService.ListAllFruitsResponse> EBarter.FruitService.FruitInventorySoap.ListAllFruitsAsync(EBarter.FruitService.ListAllFruitsRequest request) {
            return base.Channel.ListAllFruitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.FruitService.ListAllFruitsResponse> ListAllFruitsAsync() {
            EBarter.FruitService.ListAllFruitsRequest inValue = new EBarter.FruitService.ListAllFruitsRequest();
            inValue.Body = new EBarter.FruitService.ListAllFruitsRequestBody();
            return ((EBarter.FruitService.FruitInventorySoap)(this)).ListAllFruitsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.FruitService.AddFruitPriceResponse EBarter.FruitService.FruitInventorySoap.AddFruitPrice(EBarter.FruitService.AddFruitPriceRequest request) {
            return base.Channel.AddFruitPrice(request);
        }
        
        public bool AddFruitPrice(string fruitName, double minfruitPrice, EBarter.FruitService.Unit fruitUnit, double maxfruitPrice) {
            EBarter.FruitService.AddFruitPriceRequest inValue = new EBarter.FruitService.AddFruitPriceRequest();
            inValue.Body = new EBarter.FruitService.AddFruitPriceRequestBody();
            inValue.Body.fruitName = fruitName;
            inValue.Body.minfruitPrice = minfruitPrice;
            inValue.Body.fruitUnit = fruitUnit;
            inValue.Body.maxfruitPrice = maxfruitPrice;
            EBarter.FruitService.AddFruitPriceResponse retVal = ((EBarter.FruitService.FruitInventorySoap)(this)).AddFruitPrice(inValue);
            return retVal.Body.AddFruitPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.FruitService.AddFruitPriceResponse> EBarter.FruitService.FruitInventorySoap.AddFruitPriceAsync(EBarter.FruitService.AddFruitPriceRequest request) {
            return base.Channel.AddFruitPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.FruitService.AddFruitPriceResponse> AddFruitPriceAsync(string fruitName, double minfruitPrice, EBarter.FruitService.Unit fruitUnit, double maxfruitPrice) {
            EBarter.FruitService.AddFruitPriceRequest inValue = new EBarter.FruitService.AddFruitPriceRequest();
            inValue.Body = new EBarter.FruitService.AddFruitPriceRequestBody();
            inValue.Body.fruitName = fruitName;
            inValue.Body.minfruitPrice = minfruitPrice;
            inValue.Body.fruitUnit = fruitUnit;
            inValue.Body.maxfruitPrice = maxfruitPrice;
            return ((EBarter.FruitService.FruitInventorySoap)(this)).AddFruitPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.FruitService.DeleteFruitPriceResponse EBarter.FruitService.FruitInventorySoap.DeleteFruitPrice(EBarter.FruitService.DeleteFruitPriceRequest request) {
            return base.Channel.DeleteFruitPrice(request);
        }
        
        public bool DeleteFruitPrice(string fruitName) {
            EBarter.FruitService.DeleteFruitPriceRequest inValue = new EBarter.FruitService.DeleteFruitPriceRequest();
            inValue.Body = new EBarter.FruitService.DeleteFruitPriceRequestBody();
            inValue.Body.fruitName = fruitName;
            EBarter.FruitService.DeleteFruitPriceResponse retVal = ((EBarter.FruitService.FruitInventorySoap)(this)).DeleteFruitPrice(inValue);
            return retVal.Body.DeleteFruitPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.FruitService.DeleteFruitPriceResponse> EBarter.FruitService.FruitInventorySoap.DeleteFruitPriceAsync(EBarter.FruitService.DeleteFruitPriceRequest request) {
            return base.Channel.DeleteFruitPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.FruitService.DeleteFruitPriceResponse> DeleteFruitPriceAsync(string fruitName) {
            EBarter.FruitService.DeleteFruitPriceRequest inValue = new EBarter.FruitService.DeleteFruitPriceRequest();
            inValue.Body = new EBarter.FruitService.DeleteFruitPriceRequestBody();
            inValue.Body.fruitName = fruitName;
            return ((EBarter.FruitService.FruitInventorySoap)(this)).DeleteFruitPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.FruitService.UpdateFruitPriceResponse EBarter.FruitService.FruitInventorySoap.UpdateFruitPrice(EBarter.FruitService.UpdateFruitPriceRequest request) {
            return base.Channel.UpdateFruitPrice(request);
        }
        
        public bool UpdateFruitPrice(string fruitName, double minFruitPrice, double maxFruitPrice) {
            EBarter.FruitService.UpdateFruitPriceRequest inValue = new EBarter.FruitService.UpdateFruitPriceRequest();
            inValue.Body = new EBarter.FruitService.UpdateFruitPriceRequestBody();
            inValue.Body.fruitName = fruitName;
            inValue.Body.minFruitPrice = minFruitPrice;
            inValue.Body.maxFruitPrice = maxFruitPrice;
            EBarter.FruitService.UpdateFruitPriceResponse retVal = ((EBarter.FruitService.FruitInventorySoap)(this)).UpdateFruitPrice(inValue);
            return retVal.Body.UpdateFruitPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.FruitService.UpdateFruitPriceResponse> EBarter.FruitService.FruitInventorySoap.UpdateFruitPriceAsync(EBarter.FruitService.UpdateFruitPriceRequest request) {
            return base.Channel.UpdateFruitPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.FruitService.UpdateFruitPriceResponse> UpdateFruitPriceAsync(string fruitName, double minFruitPrice, double maxFruitPrice) {
            EBarter.FruitService.UpdateFruitPriceRequest inValue = new EBarter.FruitService.UpdateFruitPriceRequest();
            inValue.Body = new EBarter.FruitService.UpdateFruitPriceRequestBody();
            inValue.Body.fruitName = fruitName;
            inValue.Body.minFruitPrice = minFruitPrice;
            inValue.Body.maxFruitPrice = maxFruitPrice;
            return ((EBarter.FruitService.FruitInventorySoap)(this)).UpdateFruitPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.FruitService.CalMinFruitCostResponse EBarter.FruitService.FruitInventorySoap.CalMinFruitCost(EBarter.FruitService.CalMinFruitCostRequest request) {
            return base.Channel.CalMinFruitCost(request);
        }
        
        public double CalMinFruitCost(string fruitName, double fruitQuantity) {
            EBarter.FruitService.CalMinFruitCostRequest inValue = new EBarter.FruitService.CalMinFruitCostRequest();
            inValue.Body = new EBarter.FruitService.CalMinFruitCostRequestBody();
            inValue.Body.fruitName = fruitName;
            inValue.Body.fruitQuantity = fruitQuantity;
            EBarter.FruitService.CalMinFruitCostResponse retVal = ((EBarter.FruitService.FruitInventorySoap)(this)).CalMinFruitCost(inValue);
            return retVal.Body.CalMinFruitCostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.FruitService.CalMinFruitCostResponse> EBarter.FruitService.FruitInventorySoap.CalMinFruitCostAsync(EBarter.FruitService.CalMinFruitCostRequest request) {
            return base.Channel.CalMinFruitCostAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.FruitService.CalMinFruitCostResponse> CalMinFruitCostAsync(string fruitName, double fruitQuantity) {
            EBarter.FruitService.CalMinFruitCostRequest inValue = new EBarter.FruitService.CalMinFruitCostRequest();
            inValue.Body = new EBarter.FruitService.CalMinFruitCostRequestBody();
            inValue.Body.fruitName = fruitName;
            inValue.Body.fruitQuantity = fruitQuantity;
            return ((EBarter.FruitService.FruitInventorySoap)(this)).CalMinFruitCostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.FruitService.CalMaxFruitCostResponse EBarter.FruitService.FruitInventorySoap.CalMaxFruitCost(EBarter.FruitService.CalMaxFruitCostRequest request) {
            return base.Channel.CalMaxFruitCost(request);
        }
        
        public double CalMaxFruitCost(string fruitName, double fruitQuantity) {
            EBarter.FruitService.CalMaxFruitCostRequest inValue = new EBarter.FruitService.CalMaxFruitCostRequest();
            inValue.Body = new EBarter.FruitService.CalMaxFruitCostRequestBody();
            inValue.Body.fruitName = fruitName;
            inValue.Body.fruitQuantity = fruitQuantity;
            EBarter.FruitService.CalMaxFruitCostResponse retVal = ((EBarter.FruitService.FruitInventorySoap)(this)).CalMaxFruitCost(inValue);
            return retVal.Body.CalMaxFruitCostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.FruitService.CalMaxFruitCostResponse> EBarter.FruitService.FruitInventorySoap.CalMaxFruitCostAsync(EBarter.FruitService.CalMaxFruitCostRequest request) {
            return base.Channel.CalMaxFruitCostAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.FruitService.CalMaxFruitCostResponse> CalMaxFruitCostAsync(string fruitName, double fruitQuantity) {
            EBarter.FruitService.CalMaxFruitCostRequest inValue = new EBarter.FruitService.CalMaxFruitCostRequest();
            inValue.Body = new EBarter.FruitService.CalMaxFruitCostRequestBody();
            inValue.Body.fruitName = fruitName;
            inValue.Body.fruitQuantity = fruitQuantity;
            return ((EBarter.FruitService.FruitInventorySoap)(this)).CalMaxFruitCostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.FruitService.CheckInventoryResponse EBarter.FruitService.FruitInventorySoap.CheckInventory(EBarter.FruitService.CheckInventoryRequest request) {
            return base.Channel.CheckInventory(request);
        }
        
        public string CheckInventory(string fruitName) {
            EBarter.FruitService.CheckInventoryRequest inValue = new EBarter.FruitService.CheckInventoryRequest();
            inValue.Body = new EBarter.FruitService.CheckInventoryRequestBody();
            inValue.Body.fruitName = fruitName;
            EBarter.FruitService.CheckInventoryResponse retVal = ((EBarter.FruitService.FruitInventorySoap)(this)).CheckInventory(inValue);
            return retVal.Body.CheckInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.FruitService.CheckInventoryResponse> EBarter.FruitService.FruitInventorySoap.CheckInventoryAsync(EBarter.FruitService.CheckInventoryRequest request) {
            return base.Channel.CheckInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.FruitService.CheckInventoryResponse> CheckInventoryAsync(string fruitName) {
            EBarter.FruitService.CheckInventoryRequest inValue = new EBarter.FruitService.CheckInventoryRequest();
            inValue.Body = new EBarter.FruitService.CheckInventoryRequestBody();
            inValue.Body.fruitName = fruitName;
            return ((EBarter.FruitService.FruitInventorySoap)(this)).CheckInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.FruitService.HowMuchMinFruitResponse EBarter.FruitService.FruitInventorySoap.HowMuchMinFruit(EBarter.FruitService.HowMuchMinFruitRequest request) {
            return base.Channel.HowMuchMinFruit(request);
        }
        
        public double HowMuchMinFruit(string fruitName, double totalBudget) {
            EBarter.FruitService.HowMuchMinFruitRequest inValue = new EBarter.FruitService.HowMuchMinFruitRequest();
            inValue.Body = new EBarter.FruitService.HowMuchMinFruitRequestBody();
            inValue.Body.fruitName = fruitName;
            inValue.Body.totalBudget = totalBudget;
            EBarter.FruitService.HowMuchMinFruitResponse retVal = ((EBarter.FruitService.FruitInventorySoap)(this)).HowMuchMinFruit(inValue);
            return retVal.Body.HowMuchMinFruitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.FruitService.HowMuchMinFruitResponse> EBarter.FruitService.FruitInventorySoap.HowMuchMinFruitAsync(EBarter.FruitService.HowMuchMinFruitRequest request) {
            return base.Channel.HowMuchMinFruitAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.FruitService.HowMuchMinFruitResponse> HowMuchMinFruitAsync(string fruitName, double totalBudget) {
            EBarter.FruitService.HowMuchMinFruitRequest inValue = new EBarter.FruitService.HowMuchMinFruitRequest();
            inValue.Body = new EBarter.FruitService.HowMuchMinFruitRequestBody();
            inValue.Body.fruitName = fruitName;
            inValue.Body.totalBudget = totalBudget;
            return ((EBarter.FruitService.FruitInventorySoap)(this)).HowMuchMinFruitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.FruitService.HowMuchMaxFruitResponse EBarter.FruitService.FruitInventorySoap.HowMuchMaxFruit(EBarter.FruitService.HowMuchMaxFruitRequest request) {
            return base.Channel.HowMuchMaxFruit(request);
        }
        
        public double HowMuchMaxFruit(string fruitName, double totalBudget) {
            EBarter.FruitService.HowMuchMaxFruitRequest inValue = new EBarter.FruitService.HowMuchMaxFruitRequest();
            inValue.Body = new EBarter.FruitService.HowMuchMaxFruitRequestBody();
            inValue.Body.fruitName = fruitName;
            inValue.Body.totalBudget = totalBudget;
            EBarter.FruitService.HowMuchMaxFruitResponse retVal = ((EBarter.FruitService.FruitInventorySoap)(this)).HowMuchMaxFruit(inValue);
            return retVal.Body.HowMuchMaxFruitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.FruitService.HowMuchMaxFruitResponse> EBarter.FruitService.FruitInventorySoap.HowMuchMaxFruitAsync(EBarter.FruitService.HowMuchMaxFruitRequest request) {
            return base.Channel.HowMuchMaxFruitAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.FruitService.HowMuchMaxFruitResponse> HowMuchMaxFruitAsync(string fruitName, double totalBudget) {
            EBarter.FruitService.HowMuchMaxFruitRequest inValue = new EBarter.FruitService.HowMuchMaxFruitRequest();
            inValue.Body = new EBarter.FruitService.HowMuchMaxFruitRequestBody();
            inValue.Body.fruitName = fruitName;
            inValue.Body.totalBudget = totalBudget;
            return ((EBarter.FruitService.FruitInventorySoap)(this)).HowMuchMaxFruitAsync(inValue);
        }
    }
}
