//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBarter.ElectronicService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="ElectronicService.ElectronicsInventorySoap")]
    public interface ElectronicsInventorySoap {
        
        // CODEGEN: Generating message contract since element name ListAllElectronicsResult from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ListAllElectronics", ReplyAction="*")]
        EBarter.ElectronicService.ListAllElectronicsResponse ListAllElectronics(EBarter.ElectronicService.ListAllElectronicsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ListAllElectronics", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.ElectronicService.ListAllElectronicsResponse> ListAllElectronicsAsync(EBarter.ElectronicService.ListAllElectronicsRequest request);
        
        // CODEGEN: Generating message contract since element name electronicName from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/AddElectronicPrice", ReplyAction="*")]
        EBarter.ElectronicService.AddElectronicPriceResponse AddElectronicPrice(EBarter.ElectronicService.AddElectronicPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/AddElectronicPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.ElectronicService.AddElectronicPriceResponse> AddElectronicPriceAsync(EBarter.ElectronicService.AddElectronicPriceRequest request);
        
        // CODEGEN: Generating message contract since element name electronicName from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/DeleteElectronicPrice", ReplyAction="*")]
        EBarter.ElectronicService.DeleteElectronicPriceResponse DeleteElectronicPrice(EBarter.ElectronicService.DeleteElectronicPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/DeleteElectronicPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.ElectronicService.DeleteElectronicPriceResponse> DeleteElectronicPriceAsync(EBarter.ElectronicService.DeleteElectronicPriceRequest request);
        
        // CODEGEN: Generating message contract since element name electronicName from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/UpdateElectronicPrice", ReplyAction="*")]
        EBarter.ElectronicService.UpdateElectronicPriceResponse UpdateElectronicPrice(EBarter.ElectronicService.UpdateElectronicPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/UpdateElectronicPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.ElectronicService.UpdateElectronicPriceResponse> UpdateElectronicPriceAsync(EBarter.ElectronicService.UpdateElectronicPriceRequest request);
        
        // CODEGEN: Generating message contract since element name electronicName from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CheckInventory", ReplyAction="*")]
        EBarter.ElectronicService.CheckInventoryResponse CheckInventory(EBarter.ElectronicService.CheckInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CheckInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.ElectronicService.CheckInventoryResponse> CheckInventoryAsync(EBarter.ElectronicService.CheckInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name electronicName from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CalMinElectronicCost", ReplyAction="*")]
        EBarter.ElectronicService.CalMinElectronicCostResponse CalMinElectronicCost(EBarter.ElectronicService.CalMinElectronicCostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CalMinElectronicCost", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.ElectronicService.CalMinElectronicCostResponse> CalMinElectronicCostAsync(EBarter.ElectronicService.CalMinElectronicCostRequest request);
        
        // CODEGEN: Generating message contract since element name electronicName from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CalMaxElectronicCost", ReplyAction="*")]
        EBarter.ElectronicService.CalMaxElectronicCostResponse CalMaxElectronicCost(EBarter.ElectronicService.CalMaxElectronicCostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/CalMaxElectronicCost", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.ElectronicService.CalMaxElectronicCostResponse> CalMaxElectronicCostAsync(EBarter.ElectronicService.CalMaxElectronicCostRequest request);
        
        // CODEGEN: Generating message contract since element name elecName from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/HowMuchMinInstrument", ReplyAction="*")]
        EBarter.ElectronicService.HowMuchMinInstrumentResponse HowMuchMinInstrument(EBarter.ElectronicService.HowMuchMinInstrumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/HowMuchMinInstrument", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.ElectronicService.HowMuchMinInstrumentResponse> HowMuchMinInstrumentAsync(EBarter.ElectronicService.HowMuchMinInstrumentRequest request);
        
        // CODEGEN: Generating message contract since element name elecName from namespace http://localhost/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/HowMuchMaxInstrument", ReplyAction="*")]
        EBarter.ElectronicService.HowMuchMaxInstrumentResponse HowMuchMaxInstrument(EBarter.ElectronicService.HowMuchMaxInstrumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/HowMuchMaxInstrument", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.ElectronicService.HowMuchMaxInstrumentResponse> HowMuchMaxInstrumentAsync(EBarter.ElectronicService.HowMuchMaxInstrumentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAllElectronicsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAllElectronics", Namespace="http://localhost/", Order=0)]
        public EBarter.ElectronicService.ListAllElectronicsRequestBody Body;
        
        public ListAllElectronicsRequest() {
        }
        
        public ListAllElectronicsRequest(EBarter.ElectronicService.ListAllElectronicsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListAllElectronicsRequestBody {
        
        public ListAllElectronicsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAllElectronicsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAllElectronicsResponse", Namespace="http://localhost/", Order=0)]
        public EBarter.ElectronicService.ListAllElectronicsResponseBody Body;
        
        public ListAllElectronicsResponse() {
        }
        
        public ListAllElectronicsResponse(EBarter.ElectronicService.ListAllElectronicsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class ListAllElectronicsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ListAllElectronicsResult;
        
        public ListAllElectronicsResponseBody() {
        }
        
        public ListAllElectronicsResponseBody(string ListAllElectronicsResult) {
            this.ListAllElectronicsResult = ListAllElectronicsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddElectronicPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddElectronicPrice", Namespace="http://localhost/", Order=0)]
        public EBarter.ElectronicService.AddElectronicPriceRequestBody Body;
        
        public AddElectronicPriceRequest() {
        }
        
        public AddElectronicPriceRequest(EBarter.ElectronicService.AddElectronicPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class AddElectronicPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string electronicName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double minElectronicPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double maxElectronicPrice;
        
        public AddElectronicPriceRequestBody() {
        }
        
        public AddElectronicPriceRequestBody(string electronicName, double minElectronicPrice, double maxElectronicPrice) {
            this.electronicName = electronicName;
            this.minElectronicPrice = minElectronicPrice;
            this.maxElectronicPrice = maxElectronicPrice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddElectronicPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddElectronicPriceResponse", Namespace="http://localhost/", Order=0)]
        public EBarter.ElectronicService.AddElectronicPriceResponseBody Body;
        
        public AddElectronicPriceResponse() {
        }
        
        public AddElectronicPriceResponse(EBarter.ElectronicService.AddElectronicPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class AddElectronicPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddElectronicPriceResult;
        
        public AddElectronicPriceResponseBody() {
        }
        
        public AddElectronicPriceResponseBody(bool AddElectronicPriceResult) {
            this.AddElectronicPriceResult = AddElectronicPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteElectronicPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteElectronicPrice", Namespace="http://localhost/", Order=0)]
        public EBarter.ElectronicService.DeleteElectronicPriceRequestBody Body;
        
        public DeleteElectronicPriceRequest() {
        }
        
        public DeleteElectronicPriceRequest(EBarter.ElectronicService.DeleteElectronicPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class DeleteElectronicPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string electronicName;
        
        public DeleteElectronicPriceRequestBody() {
        }
        
        public DeleteElectronicPriceRequestBody(string electronicName) {
            this.electronicName = electronicName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteElectronicPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteElectronicPriceResponse", Namespace="http://localhost/", Order=0)]
        public EBarter.ElectronicService.DeleteElectronicPriceResponseBody Body;
        
        public DeleteElectronicPriceResponse() {
        }
        
        public DeleteElectronicPriceResponse(EBarter.ElectronicService.DeleteElectronicPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class DeleteElectronicPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteElectronicPriceResult;
        
        public DeleteElectronicPriceResponseBody() {
        }
        
        public DeleteElectronicPriceResponseBody(bool DeleteElectronicPriceResult) {
            this.DeleteElectronicPriceResult = DeleteElectronicPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateElectronicPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateElectronicPrice", Namespace="http://localhost/", Order=0)]
        public EBarter.ElectronicService.UpdateElectronicPriceRequestBody Body;
        
        public UpdateElectronicPriceRequest() {
        }
        
        public UpdateElectronicPriceRequest(EBarter.ElectronicService.UpdateElectronicPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class UpdateElectronicPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string electronicName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double EMinPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double EMaxPrice;
        
        public UpdateElectronicPriceRequestBody() {
        }
        
        public UpdateElectronicPriceRequestBody(string electronicName, double EMinPrice, double EMaxPrice) {
            this.electronicName = electronicName;
            this.EMinPrice = EMinPrice;
            this.EMaxPrice = EMaxPrice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateElectronicPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateElectronicPriceResponse", Namespace="http://localhost/", Order=0)]
        public EBarter.ElectronicService.UpdateElectronicPriceResponseBody Body;
        
        public UpdateElectronicPriceResponse() {
        }
        
        public UpdateElectronicPriceResponse(EBarter.ElectronicService.UpdateElectronicPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class UpdateElectronicPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateElectronicPriceResult;
        
        public UpdateElectronicPriceResponseBody() {
        }
        
        public UpdateElectronicPriceResponseBody(bool UpdateElectronicPriceResult) {
            this.UpdateElectronicPriceResult = UpdateElectronicPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckInventory", Namespace="http://localhost/", Order=0)]
        public EBarter.ElectronicService.CheckInventoryRequestBody Body;
        
        public CheckInventoryRequest() {
        }
        
        public CheckInventoryRequest(EBarter.ElectronicService.CheckInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CheckInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string electronicName;
        
        public CheckInventoryRequestBody() {
        }
        
        public CheckInventoryRequestBody(string electronicName) {
            this.electronicName = electronicName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckInventoryResponse", Namespace="http://localhost/", Order=0)]
        public EBarter.ElectronicService.CheckInventoryResponseBody Body;
        
        public CheckInventoryResponse() {
        }
        
        public CheckInventoryResponse(EBarter.ElectronicService.CheckInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CheckInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckInventoryResult;
        
        public CheckInventoryResponseBody() {
        }
        
        public CheckInventoryResponseBody(string CheckInventoryResult) {
            this.CheckInventoryResult = CheckInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalMinElectronicCostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalMinElectronicCost", Namespace="http://localhost/", Order=0)]
        public EBarter.ElectronicService.CalMinElectronicCostRequestBody Body;
        
        public CalMinElectronicCostRequest() {
        }
        
        public CalMinElectronicCostRequest(EBarter.ElectronicService.CalMinElectronicCostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CalMinElectronicCostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string electronicName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double electronicQnty;
        
        public CalMinElectronicCostRequestBody() {
        }
        
        public CalMinElectronicCostRequestBody(string electronicName, double electronicQnty) {
            this.electronicName = electronicName;
            this.electronicQnty = electronicQnty;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalMinElectronicCostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalMinElectronicCostResponse", Namespace="http://localhost/", Order=0)]
        public EBarter.ElectronicService.CalMinElectronicCostResponseBody Body;
        
        public CalMinElectronicCostResponse() {
        }
        
        public CalMinElectronicCostResponse(EBarter.ElectronicService.CalMinElectronicCostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CalMinElectronicCostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CalMinElectronicCostResult;
        
        public CalMinElectronicCostResponseBody() {
        }
        
        public CalMinElectronicCostResponseBody(double CalMinElectronicCostResult) {
            this.CalMinElectronicCostResult = CalMinElectronicCostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalMaxElectronicCostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalMaxElectronicCost", Namespace="http://localhost/", Order=0)]
        public EBarter.ElectronicService.CalMaxElectronicCostRequestBody Body;
        
        public CalMaxElectronicCostRequest() {
        }
        
        public CalMaxElectronicCostRequest(EBarter.ElectronicService.CalMaxElectronicCostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CalMaxElectronicCostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string electronicName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double electronicQnty;
        
        public CalMaxElectronicCostRequestBody() {
        }
        
        public CalMaxElectronicCostRequestBody(string electronicName, double electronicQnty) {
            this.electronicName = electronicName;
            this.electronicQnty = electronicQnty;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalMaxElectronicCostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalMaxElectronicCostResponse", Namespace="http://localhost/", Order=0)]
        public EBarter.ElectronicService.CalMaxElectronicCostResponseBody Body;
        
        public CalMaxElectronicCostResponse() {
        }
        
        public CalMaxElectronicCostResponse(EBarter.ElectronicService.CalMaxElectronicCostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class CalMaxElectronicCostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CalMaxElectronicCostResult;
        
        public CalMaxElectronicCostResponseBody() {
        }
        
        public CalMaxElectronicCostResponseBody(double CalMaxElectronicCostResult) {
            this.CalMaxElectronicCostResult = CalMaxElectronicCostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HowMuchMinInstrumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HowMuchMinInstrument", Namespace="http://localhost/", Order=0)]
        public EBarter.ElectronicService.HowMuchMinInstrumentRequestBody Body;
        
        public HowMuchMinInstrumentRequest() {
        }
        
        public HowMuchMinInstrumentRequest(EBarter.ElectronicService.HowMuchMinInstrumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class HowMuchMinInstrumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string elecName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double totalBudget;
        
        public HowMuchMinInstrumentRequestBody() {
        }
        
        public HowMuchMinInstrumentRequestBody(string elecName, double totalBudget) {
            this.elecName = elecName;
            this.totalBudget = totalBudget;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HowMuchMinInstrumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HowMuchMinInstrumentResponse", Namespace="http://localhost/", Order=0)]
        public EBarter.ElectronicService.HowMuchMinInstrumentResponseBody Body;
        
        public HowMuchMinInstrumentResponse() {
        }
        
        public HowMuchMinInstrumentResponse(EBarter.ElectronicService.HowMuchMinInstrumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class HowMuchMinInstrumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double HowMuchMinInstrumentResult;
        
        public HowMuchMinInstrumentResponseBody() {
        }
        
        public HowMuchMinInstrumentResponseBody(double HowMuchMinInstrumentResult) {
            this.HowMuchMinInstrumentResult = HowMuchMinInstrumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HowMuchMaxInstrumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HowMuchMaxInstrument", Namespace="http://localhost/", Order=0)]
        public EBarter.ElectronicService.HowMuchMaxInstrumentRequestBody Body;
        
        public HowMuchMaxInstrumentRequest() {
        }
        
        public HowMuchMaxInstrumentRequest(EBarter.ElectronicService.HowMuchMaxInstrumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class HowMuchMaxInstrumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string elecName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double totalBudget;
        
        public HowMuchMaxInstrumentRequestBody() {
        }
        
        public HowMuchMaxInstrumentRequestBody(string elecName, double totalBudget) {
            this.elecName = elecName;
            this.totalBudget = totalBudget;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HowMuchMaxInstrumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HowMuchMaxInstrumentResponse", Namespace="http://localhost/", Order=0)]
        public EBarter.ElectronicService.HowMuchMaxInstrumentResponseBody Body;
        
        public HowMuchMaxInstrumentResponse() {
        }
        
        public HowMuchMaxInstrumentResponse(EBarter.ElectronicService.HowMuchMaxInstrumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class HowMuchMaxInstrumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double HowMuchMaxInstrumentResult;
        
        public HowMuchMaxInstrumentResponseBody() {
        }
        
        public HowMuchMaxInstrumentResponseBody(double HowMuchMaxInstrumentResult) {
            this.HowMuchMaxInstrumentResult = HowMuchMaxInstrumentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ElectronicsInventorySoapChannel : EBarter.ElectronicService.ElectronicsInventorySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ElectronicsInventorySoapClient : System.ServiceModel.ClientBase<EBarter.ElectronicService.ElectronicsInventorySoap>, EBarter.ElectronicService.ElectronicsInventorySoap {
        
        public ElectronicsInventorySoapClient() {
        }
        
        public ElectronicsInventorySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ElectronicsInventorySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ElectronicsInventorySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ElectronicsInventorySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.ElectronicService.ListAllElectronicsResponse EBarter.ElectronicService.ElectronicsInventorySoap.ListAllElectronics(EBarter.ElectronicService.ListAllElectronicsRequest request) {
            return base.Channel.ListAllElectronics(request);
        }
        
        public string ListAllElectronics() {
            EBarter.ElectronicService.ListAllElectronicsRequest inValue = new EBarter.ElectronicService.ListAllElectronicsRequest();
            inValue.Body = new EBarter.ElectronicService.ListAllElectronicsRequestBody();
            EBarter.ElectronicService.ListAllElectronicsResponse retVal = ((EBarter.ElectronicService.ElectronicsInventorySoap)(this)).ListAllElectronics(inValue);
            return retVal.Body.ListAllElectronicsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.ElectronicService.ListAllElectronicsResponse> EBarter.ElectronicService.ElectronicsInventorySoap.ListAllElectronicsAsync(EBarter.ElectronicService.ListAllElectronicsRequest request) {
            return base.Channel.ListAllElectronicsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.ElectronicService.ListAllElectronicsResponse> ListAllElectronicsAsync() {
            EBarter.ElectronicService.ListAllElectronicsRequest inValue = new EBarter.ElectronicService.ListAllElectronicsRequest();
            inValue.Body = new EBarter.ElectronicService.ListAllElectronicsRequestBody();
            return ((EBarter.ElectronicService.ElectronicsInventorySoap)(this)).ListAllElectronicsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.ElectronicService.AddElectronicPriceResponse EBarter.ElectronicService.ElectronicsInventorySoap.AddElectronicPrice(EBarter.ElectronicService.AddElectronicPriceRequest request) {
            return base.Channel.AddElectronicPrice(request);
        }
        
        public bool AddElectronicPrice(string electronicName, double minElectronicPrice, double maxElectronicPrice) {
            EBarter.ElectronicService.AddElectronicPriceRequest inValue = new EBarter.ElectronicService.AddElectronicPriceRequest();
            inValue.Body = new EBarter.ElectronicService.AddElectronicPriceRequestBody();
            inValue.Body.electronicName = electronicName;
            inValue.Body.minElectronicPrice = minElectronicPrice;
            inValue.Body.maxElectronicPrice = maxElectronicPrice;
            EBarter.ElectronicService.AddElectronicPriceResponse retVal = ((EBarter.ElectronicService.ElectronicsInventorySoap)(this)).AddElectronicPrice(inValue);
            return retVal.Body.AddElectronicPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.ElectronicService.AddElectronicPriceResponse> EBarter.ElectronicService.ElectronicsInventorySoap.AddElectronicPriceAsync(EBarter.ElectronicService.AddElectronicPriceRequest request) {
            return base.Channel.AddElectronicPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.ElectronicService.AddElectronicPriceResponse> AddElectronicPriceAsync(string electronicName, double minElectronicPrice, double maxElectronicPrice) {
            EBarter.ElectronicService.AddElectronicPriceRequest inValue = new EBarter.ElectronicService.AddElectronicPriceRequest();
            inValue.Body = new EBarter.ElectronicService.AddElectronicPriceRequestBody();
            inValue.Body.electronicName = electronicName;
            inValue.Body.minElectronicPrice = minElectronicPrice;
            inValue.Body.maxElectronicPrice = maxElectronicPrice;
            return ((EBarter.ElectronicService.ElectronicsInventorySoap)(this)).AddElectronicPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.ElectronicService.DeleteElectronicPriceResponse EBarter.ElectronicService.ElectronicsInventorySoap.DeleteElectronicPrice(EBarter.ElectronicService.DeleteElectronicPriceRequest request) {
            return base.Channel.DeleteElectronicPrice(request);
        }
        
        public bool DeleteElectronicPrice(string electronicName) {
            EBarter.ElectronicService.DeleteElectronicPriceRequest inValue = new EBarter.ElectronicService.DeleteElectronicPriceRequest();
            inValue.Body = new EBarter.ElectronicService.DeleteElectronicPriceRequestBody();
            inValue.Body.electronicName = electronicName;
            EBarter.ElectronicService.DeleteElectronicPriceResponse retVal = ((EBarter.ElectronicService.ElectronicsInventorySoap)(this)).DeleteElectronicPrice(inValue);
            return retVal.Body.DeleteElectronicPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.ElectronicService.DeleteElectronicPriceResponse> EBarter.ElectronicService.ElectronicsInventorySoap.DeleteElectronicPriceAsync(EBarter.ElectronicService.DeleteElectronicPriceRequest request) {
            return base.Channel.DeleteElectronicPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.ElectronicService.DeleteElectronicPriceResponse> DeleteElectronicPriceAsync(string electronicName) {
            EBarter.ElectronicService.DeleteElectronicPriceRequest inValue = new EBarter.ElectronicService.DeleteElectronicPriceRequest();
            inValue.Body = new EBarter.ElectronicService.DeleteElectronicPriceRequestBody();
            inValue.Body.electronicName = electronicName;
            return ((EBarter.ElectronicService.ElectronicsInventorySoap)(this)).DeleteElectronicPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.ElectronicService.UpdateElectronicPriceResponse EBarter.ElectronicService.ElectronicsInventorySoap.UpdateElectronicPrice(EBarter.ElectronicService.UpdateElectronicPriceRequest request) {
            return base.Channel.UpdateElectronicPrice(request);
        }
        
        public bool UpdateElectronicPrice(string electronicName, double EMinPrice, double EMaxPrice) {
            EBarter.ElectronicService.UpdateElectronicPriceRequest inValue = new EBarter.ElectronicService.UpdateElectronicPriceRequest();
            inValue.Body = new EBarter.ElectronicService.UpdateElectronicPriceRequestBody();
            inValue.Body.electronicName = electronicName;
            inValue.Body.EMinPrice = EMinPrice;
            inValue.Body.EMaxPrice = EMaxPrice;
            EBarter.ElectronicService.UpdateElectronicPriceResponse retVal = ((EBarter.ElectronicService.ElectronicsInventorySoap)(this)).UpdateElectronicPrice(inValue);
            return retVal.Body.UpdateElectronicPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.ElectronicService.UpdateElectronicPriceResponse> EBarter.ElectronicService.ElectronicsInventorySoap.UpdateElectronicPriceAsync(EBarter.ElectronicService.UpdateElectronicPriceRequest request) {
            return base.Channel.UpdateElectronicPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.ElectronicService.UpdateElectronicPriceResponse> UpdateElectronicPriceAsync(string electronicName, double EMinPrice, double EMaxPrice) {
            EBarter.ElectronicService.UpdateElectronicPriceRequest inValue = new EBarter.ElectronicService.UpdateElectronicPriceRequest();
            inValue.Body = new EBarter.ElectronicService.UpdateElectronicPriceRequestBody();
            inValue.Body.electronicName = electronicName;
            inValue.Body.EMinPrice = EMinPrice;
            inValue.Body.EMaxPrice = EMaxPrice;
            return ((EBarter.ElectronicService.ElectronicsInventorySoap)(this)).UpdateElectronicPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.ElectronicService.CheckInventoryResponse EBarter.ElectronicService.ElectronicsInventorySoap.CheckInventory(EBarter.ElectronicService.CheckInventoryRequest request) {
            return base.Channel.CheckInventory(request);
        }
        
        public string CheckInventory(string electronicName) {
            EBarter.ElectronicService.CheckInventoryRequest inValue = new EBarter.ElectronicService.CheckInventoryRequest();
            inValue.Body = new EBarter.ElectronicService.CheckInventoryRequestBody();
            inValue.Body.electronicName = electronicName;
            EBarter.ElectronicService.CheckInventoryResponse retVal = ((EBarter.ElectronicService.ElectronicsInventorySoap)(this)).CheckInventory(inValue);
            return retVal.Body.CheckInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.ElectronicService.CheckInventoryResponse> EBarter.ElectronicService.ElectronicsInventorySoap.CheckInventoryAsync(EBarter.ElectronicService.CheckInventoryRequest request) {
            return base.Channel.CheckInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.ElectronicService.CheckInventoryResponse> CheckInventoryAsync(string electronicName) {
            EBarter.ElectronicService.CheckInventoryRequest inValue = new EBarter.ElectronicService.CheckInventoryRequest();
            inValue.Body = new EBarter.ElectronicService.CheckInventoryRequestBody();
            inValue.Body.electronicName = electronicName;
            return ((EBarter.ElectronicService.ElectronicsInventorySoap)(this)).CheckInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.ElectronicService.CalMinElectronicCostResponse EBarter.ElectronicService.ElectronicsInventorySoap.CalMinElectronicCost(EBarter.ElectronicService.CalMinElectronicCostRequest request) {
            return base.Channel.CalMinElectronicCost(request);
        }
        
        public double CalMinElectronicCost(string electronicName, double electronicQnty) {
            EBarter.ElectronicService.CalMinElectronicCostRequest inValue = new EBarter.ElectronicService.CalMinElectronicCostRequest();
            inValue.Body = new EBarter.ElectronicService.CalMinElectronicCostRequestBody();
            inValue.Body.electronicName = electronicName;
            inValue.Body.electronicQnty = electronicQnty;
            EBarter.ElectronicService.CalMinElectronicCostResponse retVal = ((EBarter.ElectronicService.ElectronicsInventorySoap)(this)).CalMinElectronicCost(inValue);
            return retVal.Body.CalMinElectronicCostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.ElectronicService.CalMinElectronicCostResponse> EBarter.ElectronicService.ElectronicsInventorySoap.CalMinElectronicCostAsync(EBarter.ElectronicService.CalMinElectronicCostRequest request) {
            return base.Channel.CalMinElectronicCostAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.ElectronicService.CalMinElectronicCostResponse> CalMinElectronicCostAsync(string electronicName, double electronicQnty) {
            EBarter.ElectronicService.CalMinElectronicCostRequest inValue = new EBarter.ElectronicService.CalMinElectronicCostRequest();
            inValue.Body = new EBarter.ElectronicService.CalMinElectronicCostRequestBody();
            inValue.Body.electronicName = electronicName;
            inValue.Body.electronicQnty = electronicQnty;
            return ((EBarter.ElectronicService.ElectronicsInventorySoap)(this)).CalMinElectronicCostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.ElectronicService.CalMaxElectronicCostResponse EBarter.ElectronicService.ElectronicsInventorySoap.CalMaxElectronicCost(EBarter.ElectronicService.CalMaxElectronicCostRequest request) {
            return base.Channel.CalMaxElectronicCost(request);
        }
        
        public double CalMaxElectronicCost(string electronicName, double electronicQnty) {
            EBarter.ElectronicService.CalMaxElectronicCostRequest inValue = new EBarter.ElectronicService.CalMaxElectronicCostRequest();
            inValue.Body = new EBarter.ElectronicService.CalMaxElectronicCostRequestBody();
            inValue.Body.electronicName = electronicName;
            inValue.Body.electronicQnty = electronicQnty;
            EBarter.ElectronicService.CalMaxElectronicCostResponse retVal = ((EBarter.ElectronicService.ElectronicsInventorySoap)(this)).CalMaxElectronicCost(inValue);
            return retVal.Body.CalMaxElectronicCostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.ElectronicService.CalMaxElectronicCostResponse> EBarter.ElectronicService.ElectronicsInventorySoap.CalMaxElectronicCostAsync(EBarter.ElectronicService.CalMaxElectronicCostRequest request) {
            return base.Channel.CalMaxElectronicCostAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.ElectronicService.CalMaxElectronicCostResponse> CalMaxElectronicCostAsync(string electronicName, double electronicQnty) {
            EBarter.ElectronicService.CalMaxElectronicCostRequest inValue = new EBarter.ElectronicService.CalMaxElectronicCostRequest();
            inValue.Body = new EBarter.ElectronicService.CalMaxElectronicCostRequestBody();
            inValue.Body.electronicName = electronicName;
            inValue.Body.electronicQnty = electronicQnty;
            return ((EBarter.ElectronicService.ElectronicsInventorySoap)(this)).CalMaxElectronicCostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.ElectronicService.HowMuchMinInstrumentResponse EBarter.ElectronicService.ElectronicsInventorySoap.HowMuchMinInstrument(EBarter.ElectronicService.HowMuchMinInstrumentRequest request) {
            return base.Channel.HowMuchMinInstrument(request);
        }
        
        public double HowMuchMinInstrument(string elecName, double totalBudget) {
            EBarter.ElectronicService.HowMuchMinInstrumentRequest inValue = new EBarter.ElectronicService.HowMuchMinInstrumentRequest();
            inValue.Body = new EBarter.ElectronicService.HowMuchMinInstrumentRequestBody();
            inValue.Body.elecName = elecName;
            inValue.Body.totalBudget = totalBudget;
            EBarter.ElectronicService.HowMuchMinInstrumentResponse retVal = ((EBarter.ElectronicService.ElectronicsInventorySoap)(this)).HowMuchMinInstrument(inValue);
            return retVal.Body.HowMuchMinInstrumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.ElectronicService.HowMuchMinInstrumentResponse> EBarter.ElectronicService.ElectronicsInventorySoap.HowMuchMinInstrumentAsync(EBarter.ElectronicService.HowMuchMinInstrumentRequest request) {
            return base.Channel.HowMuchMinInstrumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.ElectronicService.HowMuchMinInstrumentResponse> HowMuchMinInstrumentAsync(string elecName, double totalBudget) {
            EBarter.ElectronicService.HowMuchMinInstrumentRequest inValue = new EBarter.ElectronicService.HowMuchMinInstrumentRequest();
            inValue.Body = new EBarter.ElectronicService.HowMuchMinInstrumentRequestBody();
            inValue.Body.elecName = elecName;
            inValue.Body.totalBudget = totalBudget;
            return ((EBarter.ElectronicService.ElectronicsInventorySoap)(this)).HowMuchMinInstrumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.ElectronicService.HowMuchMaxInstrumentResponse EBarter.ElectronicService.ElectronicsInventorySoap.HowMuchMaxInstrument(EBarter.ElectronicService.HowMuchMaxInstrumentRequest request) {
            return base.Channel.HowMuchMaxInstrument(request);
        }
        
        public double HowMuchMaxInstrument(string elecName, double totalBudget) {
            EBarter.ElectronicService.HowMuchMaxInstrumentRequest inValue = new EBarter.ElectronicService.HowMuchMaxInstrumentRequest();
            inValue.Body = new EBarter.ElectronicService.HowMuchMaxInstrumentRequestBody();
            inValue.Body.elecName = elecName;
            inValue.Body.totalBudget = totalBudget;
            EBarter.ElectronicService.HowMuchMaxInstrumentResponse retVal = ((EBarter.ElectronicService.ElectronicsInventorySoap)(this)).HowMuchMaxInstrument(inValue);
            return retVal.Body.HowMuchMaxInstrumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.ElectronicService.HowMuchMaxInstrumentResponse> EBarter.ElectronicService.ElectronicsInventorySoap.HowMuchMaxInstrumentAsync(EBarter.ElectronicService.HowMuchMaxInstrumentRequest request) {
            return base.Channel.HowMuchMaxInstrumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.ElectronicService.HowMuchMaxInstrumentResponse> HowMuchMaxInstrumentAsync(string elecName, double totalBudget) {
            EBarter.ElectronicService.HowMuchMaxInstrumentRequest inValue = new EBarter.ElectronicService.HowMuchMaxInstrumentRequest();
            inValue.Body = new EBarter.ElectronicService.HowMuchMaxInstrumentRequestBody();
            inValue.Body.elecName = elecName;
            inValue.Body.totalBudget = totalBudget;
            return ((EBarter.ElectronicService.ElectronicsInventorySoap)(this)).HowMuchMaxInstrumentAsync(inValue);
        }
    }
}
