//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBarter.DrinkInventory {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Unit", Namespace="https://localhost:44330/")]
    public enum Unit : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LT = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Adet = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://localhost:44330/", ConfigurationName="DrinkInventory.DrinkInventorySoap")]
    public interface DrinkInventorySoap {
        
        // CODEGEN: Generating message contract since element name ListAllDrinksResult from namespace https://localhost:44330/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44330/ListAllDrinks", ReplyAction="*")]
        EBarter.DrinkInventory.ListAllDrinksResponse ListAllDrinks(EBarter.DrinkInventory.ListAllDrinksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44330/ListAllDrinks", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.DrinkInventory.ListAllDrinksResponse> ListAllDrinksAsync(EBarter.DrinkInventory.ListAllDrinksRequest request);
        
        // CODEGEN: Generating message contract since element name drinkName from namespace https://localhost:44330/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44330/AddDrinkPrice", ReplyAction="*")]
        EBarter.DrinkInventory.AddDrinkPriceResponse AddDrinkPrice(EBarter.DrinkInventory.AddDrinkPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44330/AddDrinkPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.DrinkInventory.AddDrinkPriceResponse> AddDrinkPriceAsync(EBarter.DrinkInventory.AddDrinkPriceRequest request);
        
        // CODEGEN: Generating message contract since element name drinkName from namespace https://localhost:44330/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44330/DeleteDrinkPrice", ReplyAction="*")]
        EBarter.DrinkInventory.DeleteDrinkPriceResponse DeleteDrinkPrice(EBarter.DrinkInventory.DeleteDrinkPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44330/DeleteDrinkPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.DrinkInventory.DeleteDrinkPriceResponse> DeleteDrinkPriceAsync(EBarter.DrinkInventory.DeleteDrinkPriceRequest request);
        
        // CODEGEN: Generating message contract since element name drinkName from namespace https://localhost:44330/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44330/UpdateDrinkPrice", ReplyAction="*")]
        EBarter.DrinkInventory.UpdateDrinkPriceResponse UpdateDrinkPrice(EBarter.DrinkInventory.UpdateDrinkPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44330/UpdateDrinkPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.DrinkInventory.UpdateDrinkPriceResponse> UpdateDrinkPriceAsync(EBarter.DrinkInventory.UpdateDrinkPriceRequest request);
        
        // CODEGEN: Generating message contract since element name drinkName from namespace https://localhost:44330/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44330/CalMinDrinkCost", ReplyAction="*")]
        EBarter.DrinkInventory.CalMinDrinkCostResponse CalMinDrinkCost(EBarter.DrinkInventory.CalMinDrinkCostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44330/CalMinDrinkCost", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.DrinkInventory.CalMinDrinkCostResponse> CalMinDrinkCostAsync(EBarter.DrinkInventory.CalMinDrinkCostRequest request);
        
        // CODEGEN: Generating message contract since element name drinkName from namespace https://localhost:44330/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44330/CalMaxDrinkCost", ReplyAction="*")]
        EBarter.DrinkInventory.CalMaxDrinkCostResponse CalMaxDrinkCost(EBarter.DrinkInventory.CalMaxDrinkCostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44330/CalMaxDrinkCost", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.DrinkInventory.CalMaxDrinkCostResponse> CalMaxDrinkCostAsync(EBarter.DrinkInventory.CalMaxDrinkCostRequest request);
        
        // CODEGEN: Generating message contract since element name drinkName from namespace https://localhost:44330/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44330/CheckInventory", ReplyAction="*")]
        EBarter.DrinkInventory.CheckInventoryResponse CheckInventory(EBarter.DrinkInventory.CheckInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44330/CheckInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.DrinkInventory.CheckInventoryResponse> CheckInventoryAsync(EBarter.DrinkInventory.CheckInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name drinkName from namespace https://localhost:44330/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44330/HowMuchMinInstrument", ReplyAction="*")]
        EBarter.DrinkInventory.HowMuchMinInstrumentResponse HowMuchMinInstrument(EBarter.DrinkInventory.HowMuchMinInstrumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44330/HowMuchMinInstrument", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.DrinkInventory.HowMuchMinInstrumentResponse> HowMuchMinInstrumentAsync(EBarter.DrinkInventory.HowMuchMinInstrumentRequest request);
        
        // CODEGEN: Generating message contract since element name drinkName from namespace https://localhost:44330/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44330/HowMuchMaxInstrument", ReplyAction="*")]
        EBarter.DrinkInventory.HowMuchMaxInstrumentResponse HowMuchMaxInstrument(EBarter.DrinkInventory.HowMuchMaxInstrumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://localhost:44330/HowMuchMaxInstrument", ReplyAction="*")]
        System.Threading.Tasks.Task<EBarter.DrinkInventory.HowMuchMaxInstrumentResponse> HowMuchMaxInstrumentAsync(EBarter.DrinkInventory.HowMuchMaxInstrumentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAllDrinksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAllDrinks", Namespace="https://localhost:44330/", Order=0)]
        public EBarter.DrinkInventory.ListAllDrinksRequestBody Body;
        
        public ListAllDrinksRequest() {
        }
        
        public ListAllDrinksRequest(EBarter.DrinkInventory.ListAllDrinksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListAllDrinksRequestBody {
        
        public ListAllDrinksRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAllDrinksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAllDrinksResponse", Namespace="https://localhost:44330/", Order=0)]
        public EBarter.DrinkInventory.ListAllDrinksResponseBody Body;
        
        public ListAllDrinksResponse() {
        }
        
        public ListAllDrinksResponse(EBarter.DrinkInventory.ListAllDrinksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost:44330/")]
    public partial class ListAllDrinksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ListAllDrinksResult;
        
        public ListAllDrinksResponseBody() {
        }
        
        public ListAllDrinksResponseBody(string ListAllDrinksResult) {
            this.ListAllDrinksResult = ListAllDrinksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDrinkPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDrinkPrice", Namespace="https://localhost:44330/", Order=0)]
        public EBarter.DrinkInventory.AddDrinkPriceRequestBody Body;
        
        public AddDrinkPriceRequest() {
        }
        
        public AddDrinkPriceRequest(EBarter.DrinkInventory.AddDrinkPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost:44330/")]
    public partial class AddDrinkPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string drinkName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double minDrinkPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double maxDrinkPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public EBarter.DrinkInventory.Unit drinkUnit;
        
        public AddDrinkPriceRequestBody() {
        }
        
        public AddDrinkPriceRequestBody(string drinkName, double minDrinkPrice, double maxDrinkPrice, EBarter.DrinkInventory.Unit drinkUnit) {
            this.drinkName = drinkName;
            this.minDrinkPrice = minDrinkPrice;
            this.maxDrinkPrice = maxDrinkPrice;
            this.drinkUnit = drinkUnit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDrinkPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDrinkPriceResponse", Namespace="https://localhost:44330/", Order=0)]
        public EBarter.DrinkInventory.AddDrinkPriceResponseBody Body;
        
        public AddDrinkPriceResponse() {
        }
        
        public AddDrinkPriceResponse(EBarter.DrinkInventory.AddDrinkPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost:44330/")]
    public partial class AddDrinkPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddDrinkPriceResult;
        
        public AddDrinkPriceResponseBody() {
        }
        
        public AddDrinkPriceResponseBody(bool AddDrinkPriceResult) {
            this.AddDrinkPriceResult = AddDrinkPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDrinkPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDrinkPrice", Namespace="https://localhost:44330/", Order=0)]
        public EBarter.DrinkInventory.DeleteDrinkPriceRequestBody Body;
        
        public DeleteDrinkPriceRequest() {
        }
        
        public DeleteDrinkPriceRequest(EBarter.DrinkInventory.DeleteDrinkPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost:44330/")]
    public partial class DeleteDrinkPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string drinkName;
        
        public DeleteDrinkPriceRequestBody() {
        }
        
        public DeleteDrinkPriceRequestBody(string drinkName) {
            this.drinkName = drinkName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDrinkPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDrinkPriceResponse", Namespace="https://localhost:44330/", Order=0)]
        public EBarter.DrinkInventory.DeleteDrinkPriceResponseBody Body;
        
        public DeleteDrinkPriceResponse() {
        }
        
        public DeleteDrinkPriceResponse(EBarter.DrinkInventory.DeleteDrinkPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost:44330/")]
    public partial class DeleteDrinkPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteDrinkPriceResult;
        
        public DeleteDrinkPriceResponseBody() {
        }
        
        public DeleteDrinkPriceResponseBody(bool DeleteDrinkPriceResult) {
            this.DeleteDrinkPriceResult = DeleteDrinkPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDrinkPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDrinkPrice", Namespace="https://localhost:44330/", Order=0)]
        public EBarter.DrinkInventory.UpdateDrinkPriceRequestBody Body;
        
        public UpdateDrinkPriceRequest() {
        }
        
        public UpdateDrinkPriceRequest(EBarter.DrinkInventory.UpdateDrinkPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost:44330/")]
    public partial class UpdateDrinkPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string drinkName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double minDrinkPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double maxDrinkPrice;
        
        public UpdateDrinkPriceRequestBody() {
        }
        
        public UpdateDrinkPriceRequestBody(string drinkName, double minDrinkPrice, double maxDrinkPrice) {
            this.drinkName = drinkName;
            this.minDrinkPrice = minDrinkPrice;
            this.maxDrinkPrice = maxDrinkPrice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDrinkPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDrinkPriceResponse", Namespace="https://localhost:44330/", Order=0)]
        public EBarter.DrinkInventory.UpdateDrinkPriceResponseBody Body;
        
        public UpdateDrinkPriceResponse() {
        }
        
        public UpdateDrinkPriceResponse(EBarter.DrinkInventory.UpdateDrinkPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost:44330/")]
    public partial class UpdateDrinkPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateDrinkPriceResult;
        
        public UpdateDrinkPriceResponseBody() {
        }
        
        public UpdateDrinkPriceResponseBody(bool UpdateDrinkPriceResult) {
            this.UpdateDrinkPriceResult = UpdateDrinkPriceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalMinDrinkCostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalMinDrinkCost", Namespace="https://localhost:44330/", Order=0)]
        public EBarter.DrinkInventory.CalMinDrinkCostRequestBody Body;
        
        public CalMinDrinkCostRequest() {
        }
        
        public CalMinDrinkCostRequest(EBarter.DrinkInventory.CalMinDrinkCostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost:44330/")]
    public partial class CalMinDrinkCostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string drinkName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double drinkQuantity;
        
        public CalMinDrinkCostRequestBody() {
        }
        
        public CalMinDrinkCostRequestBody(string drinkName, double drinkQuantity) {
            this.drinkName = drinkName;
            this.drinkQuantity = drinkQuantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalMinDrinkCostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalMinDrinkCostResponse", Namespace="https://localhost:44330/", Order=0)]
        public EBarter.DrinkInventory.CalMinDrinkCostResponseBody Body;
        
        public CalMinDrinkCostResponse() {
        }
        
        public CalMinDrinkCostResponse(EBarter.DrinkInventory.CalMinDrinkCostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost:44330/")]
    public partial class CalMinDrinkCostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CalMinDrinkCostResult;
        
        public CalMinDrinkCostResponseBody() {
        }
        
        public CalMinDrinkCostResponseBody(double CalMinDrinkCostResult) {
            this.CalMinDrinkCostResult = CalMinDrinkCostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalMaxDrinkCostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalMaxDrinkCost", Namespace="https://localhost:44330/", Order=0)]
        public EBarter.DrinkInventory.CalMaxDrinkCostRequestBody Body;
        
        public CalMaxDrinkCostRequest() {
        }
        
        public CalMaxDrinkCostRequest(EBarter.DrinkInventory.CalMaxDrinkCostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost:44330/")]
    public partial class CalMaxDrinkCostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string drinkName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double drinkQuantity;
        
        public CalMaxDrinkCostRequestBody() {
        }
        
        public CalMaxDrinkCostRequestBody(string drinkName, double drinkQuantity) {
            this.drinkName = drinkName;
            this.drinkQuantity = drinkQuantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalMaxDrinkCostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalMaxDrinkCostResponse", Namespace="https://localhost:44330/", Order=0)]
        public EBarter.DrinkInventory.CalMaxDrinkCostResponseBody Body;
        
        public CalMaxDrinkCostResponse() {
        }
        
        public CalMaxDrinkCostResponse(EBarter.DrinkInventory.CalMaxDrinkCostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost:44330/")]
    public partial class CalMaxDrinkCostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CalMaxDrinkCostResult;
        
        public CalMaxDrinkCostResponseBody() {
        }
        
        public CalMaxDrinkCostResponseBody(double CalMaxDrinkCostResult) {
            this.CalMaxDrinkCostResult = CalMaxDrinkCostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckInventory", Namespace="https://localhost:44330/", Order=0)]
        public EBarter.DrinkInventory.CheckInventoryRequestBody Body;
        
        public CheckInventoryRequest() {
        }
        
        public CheckInventoryRequest(EBarter.DrinkInventory.CheckInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost:44330/")]
    public partial class CheckInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string drinkName;
        
        public CheckInventoryRequestBody() {
        }
        
        public CheckInventoryRequestBody(string drinkName) {
            this.drinkName = drinkName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckInventoryResponse", Namespace="https://localhost:44330/", Order=0)]
        public EBarter.DrinkInventory.CheckInventoryResponseBody Body;
        
        public CheckInventoryResponse() {
        }
        
        public CheckInventoryResponse(EBarter.DrinkInventory.CheckInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost:44330/")]
    public partial class CheckInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckInventoryResult;
        
        public CheckInventoryResponseBody() {
        }
        
        public CheckInventoryResponseBody(string CheckInventoryResult) {
            this.CheckInventoryResult = CheckInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HowMuchMinInstrumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HowMuchMinInstrument", Namespace="https://localhost:44330/", Order=0)]
        public EBarter.DrinkInventory.HowMuchMinInstrumentRequestBody Body;
        
        public HowMuchMinInstrumentRequest() {
        }
        
        public HowMuchMinInstrumentRequest(EBarter.DrinkInventory.HowMuchMinInstrumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost:44330/")]
    public partial class HowMuchMinInstrumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string drinkName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double totalBudget;
        
        public HowMuchMinInstrumentRequestBody() {
        }
        
        public HowMuchMinInstrumentRequestBody(string drinkName, double totalBudget) {
            this.drinkName = drinkName;
            this.totalBudget = totalBudget;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HowMuchMinInstrumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HowMuchMinInstrumentResponse", Namespace="https://localhost:44330/", Order=0)]
        public EBarter.DrinkInventory.HowMuchMinInstrumentResponseBody Body;
        
        public HowMuchMinInstrumentResponse() {
        }
        
        public HowMuchMinInstrumentResponse(EBarter.DrinkInventory.HowMuchMinInstrumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost:44330/")]
    public partial class HowMuchMinInstrumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double HowMuchMinInstrumentResult;
        
        public HowMuchMinInstrumentResponseBody() {
        }
        
        public HowMuchMinInstrumentResponseBody(double HowMuchMinInstrumentResult) {
            this.HowMuchMinInstrumentResult = HowMuchMinInstrumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HowMuchMaxInstrumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HowMuchMaxInstrument", Namespace="https://localhost:44330/", Order=0)]
        public EBarter.DrinkInventory.HowMuchMaxInstrumentRequestBody Body;
        
        public HowMuchMaxInstrumentRequest() {
        }
        
        public HowMuchMaxInstrumentRequest(EBarter.DrinkInventory.HowMuchMaxInstrumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost:44330/")]
    public partial class HowMuchMaxInstrumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string drinkName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double totalBudget;
        
        public HowMuchMaxInstrumentRequestBody() {
        }
        
        public HowMuchMaxInstrumentRequestBody(string drinkName, double totalBudget) {
            this.drinkName = drinkName;
            this.totalBudget = totalBudget;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HowMuchMaxInstrumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HowMuchMaxInstrumentResponse", Namespace="https://localhost:44330/", Order=0)]
        public EBarter.DrinkInventory.HowMuchMaxInstrumentResponseBody Body;
        
        public HowMuchMaxInstrumentResponse() {
        }
        
        public HowMuchMaxInstrumentResponse(EBarter.DrinkInventory.HowMuchMaxInstrumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://localhost:44330/")]
    public partial class HowMuchMaxInstrumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double HowMuchMaxInstrumentResult;
        
        public HowMuchMaxInstrumentResponseBody() {
        }
        
        public HowMuchMaxInstrumentResponseBody(double HowMuchMaxInstrumentResult) {
            this.HowMuchMaxInstrumentResult = HowMuchMaxInstrumentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DrinkInventorySoapChannel : EBarter.DrinkInventory.DrinkInventorySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DrinkInventorySoapClient : System.ServiceModel.ClientBase<EBarter.DrinkInventory.DrinkInventorySoap>, EBarter.DrinkInventory.DrinkInventorySoap {
        
        public DrinkInventorySoapClient() {
        }
        
        public DrinkInventorySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DrinkInventorySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DrinkInventorySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DrinkInventorySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.DrinkInventory.ListAllDrinksResponse EBarter.DrinkInventory.DrinkInventorySoap.ListAllDrinks(EBarter.DrinkInventory.ListAllDrinksRequest request) {
            return base.Channel.ListAllDrinks(request);
        }
        
        public string ListAllDrinks() {
            EBarter.DrinkInventory.ListAllDrinksRequest inValue = new EBarter.DrinkInventory.ListAllDrinksRequest();
            inValue.Body = new EBarter.DrinkInventory.ListAllDrinksRequestBody();
            EBarter.DrinkInventory.ListAllDrinksResponse retVal = ((EBarter.DrinkInventory.DrinkInventorySoap)(this)).ListAllDrinks(inValue);
            return retVal.Body.ListAllDrinksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.DrinkInventory.ListAllDrinksResponse> EBarter.DrinkInventory.DrinkInventorySoap.ListAllDrinksAsync(EBarter.DrinkInventory.ListAllDrinksRequest request) {
            return base.Channel.ListAllDrinksAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.DrinkInventory.ListAllDrinksResponse> ListAllDrinksAsync() {
            EBarter.DrinkInventory.ListAllDrinksRequest inValue = new EBarter.DrinkInventory.ListAllDrinksRequest();
            inValue.Body = new EBarter.DrinkInventory.ListAllDrinksRequestBody();
            return ((EBarter.DrinkInventory.DrinkInventorySoap)(this)).ListAllDrinksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.DrinkInventory.AddDrinkPriceResponse EBarter.DrinkInventory.DrinkInventorySoap.AddDrinkPrice(EBarter.DrinkInventory.AddDrinkPriceRequest request) {
            return base.Channel.AddDrinkPrice(request);
        }
        
        public bool AddDrinkPrice(string drinkName, double minDrinkPrice, double maxDrinkPrice, EBarter.DrinkInventory.Unit drinkUnit) {
            EBarter.DrinkInventory.AddDrinkPriceRequest inValue = new EBarter.DrinkInventory.AddDrinkPriceRequest();
            inValue.Body = new EBarter.DrinkInventory.AddDrinkPriceRequestBody();
            inValue.Body.drinkName = drinkName;
            inValue.Body.minDrinkPrice = minDrinkPrice;
            inValue.Body.maxDrinkPrice = maxDrinkPrice;
            inValue.Body.drinkUnit = drinkUnit;
            EBarter.DrinkInventory.AddDrinkPriceResponse retVal = ((EBarter.DrinkInventory.DrinkInventorySoap)(this)).AddDrinkPrice(inValue);
            return retVal.Body.AddDrinkPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.DrinkInventory.AddDrinkPriceResponse> EBarter.DrinkInventory.DrinkInventorySoap.AddDrinkPriceAsync(EBarter.DrinkInventory.AddDrinkPriceRequest request) {
            return base.Channel.AddDrinkPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.DrinkInventory.AddDrinkPriceResponse> AddDrinkPriceAsync(string drinkName, double minDrinkPrice, double maxDrinkPrice, EBarter.DrinkInventory.Unit drinkUnit) {
            EBarter.DrinkInventory.AddDrinkPriceRequest inValue = new EBarter.DrinkInventory.AddDrinkPriceRequest();
            inValue.Body = new EBarter.DrinkInventory.AddDrinkPriceRequestBody();
            inValue.Body.drinkName = drinkName;
            inValue.Body.minDrinkPrice = minDrinkPrice;
            inValue.Body.maxDrinkPrice = maxDrinkPrice;
            inValue.Body.drinkUnit = drinkUnit;
            return ((EBarter.DrinkInventory.DrinkInventorySoap)(this)).AddDrinkPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.DrinkInventory.DeleteDrinkPriceResponse EBarter.DrinkInventory.DrinkInventorySoap.DeleteDrinkPrice(EBarter.DrinkInventory.DeleteDrinkPriceRequest request) {
            return base.Channel.DeleteDrinkPrice(request);
        }
        
        public bool DeleteDrinkPrice(string drinkName) {
            EBarter.DrinkInventory.DeleteDrinkPriceRequest inValue = new EBarter.DrinkInventory.DeleteDrinkPriceRequest();
            inValue.Body = new EBarter.DrinkInventory.DeleteDrinkPriceRequestBody();
            inValue.Body.drinkName = drinkName;
            EBarter.DrinkInventory.DeleteDrinkPriceResponse retVal = ((EBarter.DrinkInventory.DrinkInventorySoap)(this)).DeleteDrinkPrice(inValue);
            return retVal.Body.DeleteDrinkPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.DrinkInventory.DeleteDrinkPriceResponse> EBarter.DrinkInventory.DrinkInventorySoap.DeleteDrinkPriceAsync(EBarter.DrinkInventory.DeleteDrinkPriceRequest request) {
            return base.Channel.DeleteDrinkPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.DrinkInventory.DeleteDrinkPriceResponse> DeleteDrinkPriceAsync(string drinkName) {
            EBarter.DrinkInventory.DeleteDrinkPriceRequest inValue = new EBarter.DrinkInventory.DeleteDrinkPriceRequest();
            inValue.Body = new EBarter.DrinkInventory.DeleteDrinkPriceRequestBody();
            inValue.Body.drinkName = drinkName;
            return ((EBarter.DrinkInventory.DrinkInventorySoap)(this)).DeleteDrinkPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.DrinkInventory.UpdateDrinkPriceResponse EBarter.DrinkInventory.DrinkInventorySoap.UpdateDrinkPrice(EBarter.DrinkInventory.UpdateDrinkPriceRequest request) {
            return base.Channel.UpdateDrinkPrice(request);
        }
        
        public bool UpdateDrinkPrice(string drinkName, double minDrinkPrice, double maxDrinkPrice) {
            EBarter.DrinkInventory.UpdateDrinkPriceRequest inValue = new EBarter.DrinkInventory.UpdateDrinkPriceRequest();
            inValue.Body = new EBarter.DrinkInventory.UpdateDrinkPriceRequestBody();
            inValue.Body.drinkName = drinkName;
            inValue.Body.minDrinkPrice = minDrinkPrice;
            inValue.Body.maxDrinkPrice = maxDrinkPrice;
            EBarter.DrinkInventory.UpdateDrinkPriceResponse retVal = ((EBarter.DrinkInventory.DrinkInventorySoap)(this)).UpdateDrinkPrice(inValue);
            return retVal.Body.UpdateDrinkPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.DrinkInventory.UpdateDrinkPriceResponse> EBarter.DrinkInventory.DrinkInventorySoap.UpdateDrinkPriceAsync(EBarter.DrinkInventory.UpdateDrinkPriceRequest request) {
            return base.Channel.UpdateDrinkPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.DrinkInventory.UpdateDrinkPriceResponse> UpdateDrinkPriceAsync(string drinkName, double minDrinkPrice, double maxDrinkPrice) {
            EBarter.DrinkInventory.UpdateDrinkPriceRequest inValue = new EBarter.DrinkInventory.UpdateDrinkPriceRequest();
            inValue.Body = new EBarter.DrinkInventory.UpdateDrinkPriceRequestBody();
            inValue.Body.drinkName = drinkName;
            inValue.Body.minDrinkPrice = minDrinkPrice;
            inValue.Body.maxDrinkPrice = maxDrinkPrice;
            return ((EBarter.DrinkInventory.DrinkInventorySoap)(this)).UpdateDrinkPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.DrinkInventory.CalMinDrinkCostResponse EBarter.DrinkInventory.DrinkInventorySoap.CalMinDrinkCost(EBarter.DrinkInventory.CalMinDrinkCostRequest request) {
            return base.Channel.CalMinDrinkCost(request);
        }
        
        public double CalMinDrinkCost(string drinkName, double drinkQuantity) {
            EBarter.DrinkInventory.CalMinDrinkCostRequest inValue = new EBarter.DrinkInventory.CalMinDrinkCostRequest();
            inValue.Body = new EBarter.DrinkInventory.CalMinDrinkCostRequestBody();
            inValue.Body.drinkName = drinkName;
            inValue.Body.drinkQuantity = drinkQuantity;
            EBarter.DrinkInventory.CalMinDrinkCostResponse retVal = ((EBarter.DrinkInventory.DrinkInventorySoap)(this)).CalMinDrinkCost(inValue);
            return retVal.Body.CalMinDrinkCostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.DrinkInventory.CalMinDrinkCostResponse> EBarter.DrinkInventory.DrinkInventorySoap.CalMinDrinkCostAsync(EBarter.DrinkInventory.CalMinDrinkCostRequest request) {
            return base.Channel.CalMinDrinkCostAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.DrinkInventory.CalMinDrinkCostResponse> CalMinDrinkCostAsync(string drinkName, double drinkQuantity) {
            EBarter.DrinkInventory.CalMinDrinkCostRequest inValue = new EBarter.DrinkInventory.CalMinDrinkCostRequest();
            inValue.Body = new EBarter.DrinkInventory.CalMinDrinkCostRequestBody();
            inValue.Body.drinkName = drinkName;
            inValue.Body.drinkQuantity = drinkQuantity;
            return ((EBarter.DrinkInventory.DrinkInventorySoap)(this)).CalMinDrinkCostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.DrinkInventory.CalMaxDrinkCostResponse EBarter.DrinkInventory.DrinkInventorySoap.CalMaxDrinkCost(EBarter.DrinkInventory.CalMaxDrinkCostRequest request) {
            return base.Channel.CalMaxDrinkCost(request);
        }
        
        public double CalMaxDrinkCost(string drinkName, double drinkQuantity) {
            EBarter.DrinkInventory.CalMaxDrinkCostRequest inValue = new EBarter.DrinkInventory.CalMaxDrinkCostRequest();
            inValue.Body = new EBarter.DrinkInventory.CalMaxDrinkCostRequestBody();
            inValue.Body.drinkName = drinkName;
            inValue.Body.drinkQuantity = drinkQuantity;
            EBarter.DrinkInventory.CalMaxDrinkCostResponse retVal = ((EBarter.DrinkInventory.DrinkInventorySoap)(this)).CalMaxDrinkCost(inValue);
            return retVal.Body.CalMaxDrinkCostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.DrinkInventory.CalMaxDrinkCostResponse> EBarter.DrinkInventory.DrinkInventorySoap.CalMaxDrinkCostAsync(EBarter.DrinkInventory.CalMaxDrinkCostRequest request) {
            return base.Channel.CalMaxDrinkCostAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.DrinkInventory.CalMaxDrinkCostResponse> CalMaxDrinkCostAsync(string drinkName, double drinkQuantity) {
            EBarter.DrinkInventory.CalMaxDrinkCostRequest inValue = new EBarter.DrinkInventory.CalMaxDrinkCostRequest();
            inValue.Body = new EBarter.DrinkInventory.CalMaxDrinkCostRequestBody();
            inValue.Body.drinkName = drinkName;
            inValue.Body.drinkQuantity = drinkQuantity;
            return ((EBarter.DrinkInventory.DrinkInventorySoap)(this)).CalMaxDrinkCostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.DrinkInventory.CheckInventoryResponse EBarter.DrinkInventory.DrinkInventorySoap.CheckInventory(EBarter.DrinkInventory.CheckInventoryRequest request) {
            return base.Channel.CheckInventory(request);
        }
        
        public string CheckInventory(string drinkName) {
            EBarter.DrinkInventory.CheckInventoryRequest inValue = new EBarter.DrinkInventory.CheckInventoryRequest();
            inValue.Body = new EBarter.DrinkInventory.CheckInventoryRequestBody();
            inValue.Body.drinkName = drinkName;
            EBarter.DrinkInventory.CheckInventoryResponse retVal = ((EBarter.DrinkInventory.DrinkInventorySoap)(this)).CheckInventory(inValue);
            return retVal.Body.CheckInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.DrinkInventory.CheckInventoryResponse> EBarter.DrinkInventory.DrinkInventorySoap.CheckInventoryAsync(EBarter.DrinkInventory.CheckInventoryRequest request) {
            return base.Channel.CheckInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.DrinkInventory.CheckInventoryResponse> CheckInventoryAsync(string drinkName) {
            EBarter.DrinkInventory.CheckInventoryRequest inValue = new EBarter.DrinkInventory.CheckInventoryRequest();
            inValue.Body = new EBarter.DrinkInventory.CheckInventoryRequestBody();
            inValue.Body.drinkName = drinkName;
            return ((EBarter.DrinkInventory.DrinkInventorySoap)(this)).CheckInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.DrinkInventory.HowMuchMinInstrumentResponse EBarter.DrinkInventory.DrinkInventorySoap.HowMuchMinInstrument(EBarter.DrinkInventory.HowMuchMinInstrumentRequest request) {
            return base.Channel.HowMuchMinInstrument(request);
        }
        
        public double HowMuchMinInstrument(string drinkName, double totalBudget) {
            EBarter.DrinkInventory.HowMuchMinInstrumentRequest inValue = new EBarter.DrinkInventory.HowMuchMinInstrumentRequest();
            inValue.Body = new EBarter.DrinkInventory.HowMuchMinInstrumentRequestBody();
            inValue.Body.drinkName = drinkName;
            inValue.Body.totalBudget = totalBudget;
            EBarter.DrinkInventory.HowMuchMinInstrumentResponse retVal = ((EBarter.DrinkInventory.DrinkInventorySoap)(this)).HowMuchMinInstrument(inValue);
            return retVal.Body.HowMuchMinInstrumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.DrinkInventory.HowMuchMinInstrumentResponse> EBarter.DrinkInventory.DrinkInventorySoap.HowMuchMinInstrumentAsync(EBarter.DrinkInventory.HowMuchMinInstrumentRequest request) {
            return base.Channel.HowMuchMinInstrumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.DrinkInventory.HowMuchMinInstrumentResponse> HowMuchMinInstrumentAsync(string drinkName, double totalBudget) {
            EBarter.DrinkInventory.HowMuchMinInstrumentRequest inValue = new EBarter.DrinkInventory.HowMuchMinInstrumentRequest();
            inValue.Body = new EBarter.DrinkInventory.HowMuchMinInstrumentRequestBody();
            inValue.Body.drinkName = drinkName;
            inValue.Body.totalBudget = totalBudget;
            return ((EBarter.DrinkInventory.DrinkInventorySoap)(this)).HowMuchMinInstrumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EBarter.DrinkInventory.HowMuchMaxInstrumentResponse EBarter.DrinkInventory.DrinkInventorySoap.HowMuchMaxInstrument(EBarter.DrinkInventory.HowMuchMaxInstrumentRequest request) {
            return base.Channel.HowMuchMaxInstrument(request);
        }
        
        public double HowMuchMaxInstrument(string drinkName, double totalBudget) {
            EBarter.DrinkInventory.HowMuchMaxInstrumentRequest inValue = new EBarter.DrinkInventory.HowMuchMaxInstrumentRequest();
            inValue.Body = new EBarter.DrinkInventory.HowMuchMaxInstrumentRequestBody();
            inValue.Body.drinkName = drinkName;
            inValue.Body.totalBudget = totalBudget;
            EBarter.DrinkInventory.HowMuchMaxInstrumentResponse retVal = ((EBarter.DrinkInventory.DrinkInventorySoap)(this)).HowMuchMaxInstrument(inValue);
            return retVal.Body.HowMuchMaxInstrumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EBarter.DrinkInventory.HowMuchMaxInstrumentResponse> EBarter.DrinkInventory.DrinkInventorySoap.HowMuchMaxInstrumentAsync(EBarter.DrinkInventory.HowMuchMaxInstrumentRequest request) {
            return base.Channel.HowMuchMaxInstrumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<EBarter.DrinkInventory.HowMuchMaxInstrumentResponse> HowMuchMaxInstrumentAsync(string drinkName, double totalBudget) {
            EBarter.DrinkInventory.HowMuchMaxInstrumentRequest inValue = new EBarter.DrinkInventory.HowMuchMaxInstrumentRequest();
            inValue.Body = new EBarter.DrinkInventory.HowMuchMaxInstrumentRequestBody();
            inValue.Body.drinkName = drinkName;
            inValue.Body.totalBudget = totalBudget;
            return ((EBarter.DrinkInventory.DrinkInventorySoap)(this)).HowMuchMaxInstrumentAsync(inValue);
        }
    }
}
